### PR TITLE
Fix Copy/Paste behaviour

### LINKED ISSUE #40: Bug: keep styles on copy / paste
See https://twitter.com/steventey/status/1567956854801833984

### PR DESCRIPTION
**Pull request by matthewlipski**
Currently, pasting content in the editor results in improper formatting in most cases. This PR fixes these bugs, so that the formatting of clipboard content is preserved when pasting it into the editor.

Closes #40

### CODE REVIEW

File: packages/core/src/extensions/Blocks/nodes/Block.ts [hunk 1]
```diff
@@ -60,6 +60,7 @@ export const Block = Node.create<IBlock>({
     return {
       listType: {
         default: undefined,
+        // Causes nesting issues pasting outside editor
```
Comment (YousefED) [inline packages/core/src/extensions/Blocks/nodes/Block.ts:63]: can you explain this / is this still accurate?

File: packages/core/src/extensions/Blocks/nodes/Block.ts [hunk 2]
```diff
@@ -98,25 +99,83 @@ export const Block = Node.create<IBlock>({
...
     return [
+      // For all content copied from within the editor.
       {
         tag: "div",
+        getAttrs: (element) => {
+          if (typeof element === "string") {
+            return false;
+          }
+
+          if (element.getAttribute("node") === "block") {
```
Comment (YousefED) [inline packages/core/src/extensions/Blocks/nodes/Block.ts:112]: My proposal would be to use data- attributes for this, I think it's a best practice; https://www.w3schools.com/tags/att_data-.asp

i.e.: data-bn-type (`bn-type` indicates it's the blocknote type)

File: packages/core/src/extensions/Blocks/nodes/Block.ts [hunk 3]
```diff
@@ -98,25 +99,83 @@ export const Block = Node.create<IBlock>({
...
+            return false;
+          }
+
+          let ancestor = element.parentElement;
+
+          if (ancestor === null) {
+            return false;
+          }
+
+          while (ancestor.tagName !== "B") {
```
Comment (YousefED) [inline packages/core/src/extensions/Blocks/nodes/Block.ts:151]: this while doesn't make sense? ancestor is never changed?

File: packages/core/src/extensions/Blocks/nodes/Block.ts [hunk 4]
```diff
@@ -98,25 +99,83 @@ export const Block = Node.create<IBlock>({
...
     ];
   },
 
-  renderHTML({ HTMLAttributes }) {
+  renderHTML({HTMLAttributes}) {
     return [
       "div",
       mergeAttributes(this.options.HTMLAttributes, HTMLAttributes, {
         class: styles.blockOuter,
+        node: "block-outer"
```
Comment (YousefED) [inline packages/core/src/extensions/Blocks/nodes/Block.ts:172]: (same about the data- attribute)

File: packages/core/src/extensions/Blocks/nodes/Block.ts [hunk 5]
```diff
@@ -149,89 +208,89 @@ export const Block = Node.create<IBlock>({
...
   },
 
   addCommands() {
     return {
       setBlockHeading:
         (attributes) =>
-        ({ tr, dispatch }) => {
-          return setBlockHeading(tr, dispatch, attributes.level);
-        },
+          ({tr, dispatch}) => {
```
Comment (YousefED) [inline packages/core/src/extensions/Blocks/nodes/Block.ts:219]: I think there are still some formatting-only changes here

File: packages/core/src/extensions/Blocks/nodes/BlockGroup.ts [hunk 6]
```diff
@@ -13,14 +13,30 @@ export const BlockGroup = Node.create({
...
+    return [
+      {
+        tag: "div",
+        getAttrs: (element) => {
+          if(typeof element === "string") {
+            return false;
+          }
+
+          if(element.getAttribute("node") === "block-group") {
+            return null;
```
Comment (YousefED) [inline packages/core/src/extensions/Blocks/nodes/BlockGroup.ts:25]: also comment why `return null` here (like you've done for the other nodes)

**Review by YousefED — CHANGES_REQUESTED** [review]
Nice, this seems to work well :)

Would be great if we can add playwright tests for this as well. Have you been able to get those working locally?

File: packages/core/src/extensions/Blocks/nodes/Block.ts (hunk 1 above)
Comment (matthewlipski) [reply packages/core/src/extensions/Blocks/nodes/Block.ts:63]: Yeah, lists copied from BlockNote don't get formatted properly in other apps - I'm pretty sure it's down to the fact that we don't use _ul_ or _ol_ tags to mark the start and end of a list. Copying a list from BlockNote and pasting it in e.g. Google Docs therefore makes list  items get reformatted as paragraphs, so nesting also doesn't work. Not sure if this is currently relevant right now though.

File: packages/core/src/extensions/Blocks/nodes/Block.ts (hunk 3 above)
Comment (matthewlipski) [reply packages/core/src/extensions/Blocks/nodes/Block.ts:151]: Whoops, it was supposed to traverse up the DOM tree until it finds an ancestor that's a list. I guess it's not needed either way since list items always have a list as a parent.

**Review by YousefED — APPROVED** [review]
Great stuff!

**Comment by sunillarsson** [comment]
when using copy/paste functions from different websites the results seem to be a bit so so. Using chatgpts copy function strips the line breaks etc. in blocknote.
